### PR TITLE
fixed  #252 coordinates of turtle changes after resizing the windows

### LINKED ISSUE #252: Coordinates of turtle changes after resizing the window
Angle of turtle as well as its cartesian coordinate should not be changed  even after resizing the window. So labeling of bitmap should be changed to get correct coordinates.

### PR DESCRIPTION
**Pull request by dvijeshpatel**
screenshot from 2016-02-22 22 40 22
screenshot from 2016-02-22 22 40 38

### CODE REVIEW

**Comment by walterbender** [comment]
Please see my comments in line.

**Comment by dvijeshpatel** [comment]
sorry for late reply.
in master  branch there is issue that i opened." Before and after resizing turtle position changes #258 "
i commented in commit.

**Comment by dvijeshpatel** [comment]
main point in onResize function:
we have following container(1) main canvas four activity.js(2) we passed this canvas to arguments of trashcan(3) argument of turtles(3) blocks (4)palettes while calling** init** function in activity.js. So all must have to become windows size while resizing.So "=" operator for them to become windows size.

**Comment by walterbender** [comment]
I am really confused. What is the challenges button code doing here?

**Comment by dvijeshpatel** [comment]
dvijeshpatel/TurtleBlockConfusion-JS my code link is this for TurtleBlockConfusion  javascript activity.In this there is activity.js file i make method show challenges. and also made a button using 'ta-open' icon. when button clicks all challengs are shown in canvas
|   |
|   |  |   |   |   |   |   |
| dvijeshpatel/TurtleBlockConfusion-JSContribute to TurtleBlockConfusion-JS development by creating an account on GitHub. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


 

    On Tuesday, February 23, 2016 12:54 AM, Walter Bender <notifications@github.com> wrote:
 

 Please see my comments in line.—

**Comment by dvijeshpatel** [comment]
**https://github.com/dvijeshpatel/TurtleBlockConfusion-JS**  my code link is this for TurtleBlockConfusion  javascript activity.
In this there is activity.js file i make method show challenges. and also made a button using 'ta-open' icon. when button clicks all challengs are shown in canvas

**Comment by dvijeshpatel** [comment]
showchalleneges method

**Comment by dvijeshpatel** [comment]
Sir, my code link is **https://github.com/dvijeshpatel/TurtleBlockConfusion-JS.git**

**Comment by dvijeshpatel** [comment]
There is method showChallenges.
showchallengesmethod

**Comment by dvijeshpatel** [comment]
I have create folder Challenges in code i stores all 40 challenges icon when i click button it opens end set visible all challenges to canvas from them we have to choose problem.
clickingbuttoon ta-open

**Comment by dvijeshpatel** [comment]
i need to set event Handler for all 40 images of challenges so after clicking one of them clicked images shown in windows in larger size and other disappear. I searched lot for using createjs but not yet find proper way

**Comment by dvijeshpatel** [comment]
This is work i am doing for making turtleconfusion javascript version

**Comment by dvijeshpatel** [comment]
for fixing **252 **i commits above after editing
https://github.com/dvijeshpatel/turtleblocksjs.git commits 32a0b24

**Comment by dvijeshpatel** [comment]
and also commit 481f77

**Comment by walterbender** [comment]
We solved this in a different way. Thx.

**Pull request closed without merging**
