### PR TITLE
Fixes #280 - new run menu (toolbar size reduced)

### LINKED ISSUE #280: redesign of Run buttons
The run buttons (fast, slow, step) take up a lot of room on the toolbar. Maybe there is a way to show just one button at a time? A long press could be used to open a panel for selecting other options. One question is how does the user discover this ability?

### PR DESCRIPTION
**Pull request by tradzik**
Fixes #280. User gets information about usage of run menu in help and onhover suggestions.

### CODE REVIEW

**Comment by i5o** [comment]
Hello. 

Can you replace "tabs" for "spaces"? You may want to check your ide configuration.

**Comment by walterbender** [comment]
Please save the SVG as simple SVG to remove the Inkscape "spam".

**Comment by tradzik** [comment]
@i5o Thanks, I have done it. 

@walterbender Thank you for your comment, SVG size has been reduced.

**Comment by tradzik** [comment]
I have squashed my commits into one.

**Comment by i5o** [comment]
Looks good to me.

**Comment by walterbender** [comment]
Would be better if the icon of the current play button was always the icon displayed.

**Comment by tradzik** [comment]
@walterbender Thank you for your message, I implemented this solution as I believed it is a simple and good way to fix issue #280. However, wanting to provide you with high-quality solutions meeting your requirements (I don't like leaving something unfinished), I can work and will work on changes you mentioned even without claiming a task when I finish one localization job at Sugarizer.

**Pull request merged**
