### PR TITLE
Add a "planet" that lets you manage and download projects

### PR DESCRIPTION
**Pull request by SAMdroid-apps**
It is a little rough around the edges and there is much room for improvement, but it has reached a level where it is a feature parity with the current samples viewer.  And the branch is very out of sync now :(

### CODE REVIEW

**Comment by walterbender** [comment]
In general, this is great. I haven't delved deep into the code yet, but I do have a few questions: I understand the the save/load buttons on the right are subsumed by the planet, but what happened to the trash can (delete all and undo) buttons?

**Comment by SAMdroid-apps** [comment]
Delete all:  now you can delete a whole project from the planet.  This is in effect the same?

Undo:  oops, shouldn't have deleted that :)

**Comment by walterbender** [comment]
Not quite the same thing. Delete deletes the current project, not the
project as saved on the server. There wasn't a way to delete from the
server before. FYI, I am fixing the saveSVG code... regressed. It is
causing bad thumbnails to be generated.

On Tue, Feb 17, 2015 at 2:58 PM, Sam <notifications@github.com> wrote:

> Delete all: now you can delete a whole project from the planet. This is in
> effect the same?
>
> Undo: oops, shouldn't have deleted that :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-74740513>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by SAMdroid-apps** [comment]
This delete delete your local save of that project.  There is no way to
delete a server project in this patch.

BTW: only the worldwide projects are from the server, the rest are from
localstorage

**Comment by walterbender** [comment]
We do want to let users save to the server, so that they can share projects
with each other.

On Tue, Feb 17, 2015 at 3:07 PM, Sam <notifications@github.com> wrote:

> This delete delete your local save of that project. There is no way to
> delete a server project in this patch.
>
> BTW: only the worldwide projects are from the server, the rest are from
> localstorage
>
> On Wed, 18 Feb 2015 7:05 am Walter Bender <notifications@github.com>
> wrote:
>
> > Not quite the same thing. Delete deletes the current project, not the
> > project as saved on the server. There wasn't a way to delete from the
> > server before. FYI, I am fixing the saveSVG code... regressed. It is
> > causing bad thumbnails to be generated.
> >
> > On Tue, Feb 17, 2015 at 2:58 PM, Sam <notifications@github.com> wrote:
> >
> > > Delete all: now you can delete a whole project from the planet. This is
> > in
> > > effect the same?
> > >
> > > Undo: oops, shouldn't have deleted that :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-74740513
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Walter Bender
> > Sugar Labs
> > http://www.sugarlabs.org
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-74741762
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-74742189>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by SAMdroid-apps** [comment]
I just pushed a few fixes that were discussed @walterbender

As for sharing, here is how it works:

* First section is stored locally.  People can press "publish" button to save to the server
* 2nd section is from the server.  People can click one of them to load them into a new (locally saved) project

**Comment by SAMdroid-apps** [comment]
@walterbender, do I need to make any changes?

**Comment by walterbender** [comment]
Just a couple of small details: (1) please add the erase all button. It is
to erase the current set of blocks on the screen -- nothing to do with what
you save or load; (2) I think the planet button should move to the right
side menu. Any idea if this will work from Android?

On Wed, Feb 18, 2015 at 3:05 PM, Sam <notifications@github.com> wrote:

> @walterbender <https://github.com/walterbender>, do I need to make any
> changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-74937535>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by SAMdroid-apps** [comment]
I still disagree with the need for a clear button, but I re-added it anyway.

**Comment by SAMdroid-apps** [comment]
Create a new project :)

**Comment by walterbender** [comment]
Ah.... from the button on the top right? That works. But that icon was not found so I hadn't noticed it. I that case, I agree, we don't need the delete all button.

I'm getting weird behavior trying to load projects a second time. Can you try it?

**Comment by walterbender** [comment]
After loading a few projects I start getting errors, such as:

putting vspace in the trash
http://rawgit.com/SAMdroid-apps/turtleblocksjs/material-community/images/turtle-1.svg Failed to load resource: the server responded with a status of 404 (Not Found)
activity.js:809 overwriting session data
logo.js:319 running from turtle 1
activity.js:809 overwriting session data
samplesviewer.js:66 Uncaught TypeError: Cannot read property 'replace' of undefined
activity.js:719 start blk 0 value is 0
activity.js:722 sending turtle 0 to trash
activity.js:719 start blk 26 value is 1
activity.js:722 sending turtle 1 to trash
activity.js:809 overwriting session data
https://cors-anywhere.herokuapp.com/turtle.sugarlabs.org/server/undefined Failed to load resource: the server responded with a status of 404 (Not Found)
3activity.js:765 calling toggleCollapsibles
http://rawgit.com/SAMdroid-apps/turtleblocksjs/material-community/images/turtle-1.svg Failed to load resource: the server responded with a status of 404 (Not Found)
activity.js:809 overwriting session data
samplesviewer.js:66 Uncaught TypeError: Cannot read property 'replace' of undefined
activity.js:719 start blk 0 value is 0
activity.js:722 sending turtle 0 to trash
activity.js:719 start blk 26 value is 1
activity.js:722 sending turtle 1 to trash
activity.js:809 overwriting session data
https://cors-anywhere.herokuapp.com/turtle.sugarlabs.org/server/undefined Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by walterbender** [comment]
Also, if the background changes it can result in illegible labels. Maybe set a consistent background for this view?

**Comment by SAMdroid-apps** [comment]
Ok, pushed a lot of those fixes.  I couldn't reproduce the issue with the projects not loading the 2nd time.  Could you please explain a little more.

I also found some issues with how doSVG does not generate a svg if you have not ran the turtle.  I might need to change that for this usage, because doSVG is being called pre-run.

**Comment by walterbender** [comment]
I'll take a look. Re doSVG, is the idea that you want to generate a preview
of the project by running a function? (Python version does this.) One
caveat is that some projects have forever loops and some projects have user
intervention.

On Fri, Feb 20, 2015 at 2:22 AM, Sam <notifications@github.com> wrote:

> Ok, pushed a lot of those fixes. I couldn't reproduce the issue with the
> projects not loading the 2nd time. Could you please explain a little more.
>
> I also found some issues with how doSVG does not generate a svg if you
> have not ran the turtle. I might need to change that for this usage,
> because doSVG is being called pre-run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-75199371>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by walterbender** [comment]
I just pushed a patch to master that lets some malformed projects load,
which should help with robustness of the planet, but we need some better
recovery mechanism when projects fail to load... something to think about.

On Fri, Feb 20, 2015 at 8:14 AM, Walter Bender <walter.bender@gmail.com>
wrote:

> I'll take a look. Re doSVG, is the idea that you want to generate a
> preview of the project by running a function? (Python version does this.)
> One caveat is that some projects have forever loops and some projects have
> user intervention.
>
> On Fri, Feb 20, 2015 at 2:22 AM, Sam <notifications@github.com> wrote:
>
>> Ok, pushed a lot of those fixes. I couldn't reproduce the issue with the
>> projects not loading the 2nd time. Could you please explain a little more.
>>
>> I also found some issues with how doSVG does not generate a svg if you
>> have not ran the turtle. I might need to change that for this usage,
>> because doSVG is being called pre-run.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/walterbender/turtleblocksjs/pull/168#issuecomment-75199371>
>> .
>>
>
>
>
> --
> Walter Bender
> Sugar Labs
> http://www.sugarlabs.org
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by SAMdroid-apps** [comment]
> I'll take a look. Re doSVG, is the idea that you want to generate a preview of the project by running a function? (Python version does this.) One caveat is that some projects have forever loops and some projects have user intervention.

Yeah.  I did a patch which only does a preview if there is something on the screen.

**Pull request merged**
