### PR TITLE
Broken Planet Resolved

### PR DESCRIPTION
**Pull request by abhinavanurag18**
I hope this patch works.
As it matches for the index of 'undefined', it will work as long as there is no 'undefined' in the src text of the thumbnail image of the project.

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
I actually think we need to fix the race conditions with the recursive loop thingo to fix this bug.  Don't just hide the bug :)

**Comment by SAMdroid-apps** [comment]
(So we need to make the server send pngs, not b64 pngs)

**Comment by abhinavanurag18** [comment]
I was forced to do this as the response I was getting from server was file:///...../undefined. Do I have any other choice when I cant control server's response? 
Wondering

**Comment by SAMdroid-apps** [comment]
Huh?

**Comment by abhinavanurag18** [comment]
@SAMdroid-apps  Try alerting the response from the server

**Comment by SAMdroid-apps** [comment]
Sorry, what was the request?  What was the response?

**Comment by SAMdroid-apps** [comment]
I see it is happening.  Do you know what is causing this?

**Comment by abhinavanurag18** [comment]
@SAMdroid-apps Maybe the server entries for Card-36 and My_Project can give us a lead.

**Comment by SAMdroid-apps** [comment]
This got merged right?  Can we close the pr?

**Comment by walterbender** [comment]
The PR didn't close? strange.

On Sun, Mar 8, 2015 at 5:44 PM, Sam <notifications@github.com> wrote:

> This got merged right? Can we close the pr?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/189#issuecomment-77776297>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Pull request closed without merging**
