### PR TITLE
Improve code conventions

### PR DESCRIPTION
**Pull request by erilyth**
It is generally prefered to use "===" instead of "==" in javascript for testing equality since we don't want any type conversion to be taking place while checking for equality.

### CODE REVIEW

**Comment by walterbender** [comment]
What about != to !== Will that be in a separate patch? Might make sense to have just one patch.

**Comment by erilyth** [comment]
Oh yeah sure Ill get that done as well.

**Comment by erilyth** [comment]
I changed != to !== in all places except when we check != null and != undefined since typecast checking them with !== is leading to many errors.

**Comment by walterbender** [comment]
Interesting discussion here:

http://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in

Maybe we can handle the undefined cases a bit differently.

On Fri, Dec 11, 2015 at 11:53 AM, Batchu Venkat Vishal <
notifications@github.com> wrote:

> I changed != to !== in all places except when we check != null and !=
> undefined since typecast checking them with !== is leading to many errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/246#issuecomment-163988886>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by erilyth** [comment]
For the undefined cases would the "typeof variable !== 'undefined' work" as it says in the link you provided work fine?
For null I guess just keeping it as != should be fine.

**Comment by walterbender** [comment]
typeof variable !== 'undefined'  should work, but just testing for the
varialble should work for != null
if(foo)  is the same as if(foo!=null)

On Fri, Dec 11, 2015 at 12:35 PM, Batchu Venkat Vishal <
notifications@github.com> wrote:

> For the undefined cases would the "typeof variable !== 'undefined' work"
> as it says in the link you provided work fine?
> For null I guess just keeping it as != should be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/246#issuecomment-163999018>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by erilyth** [comment]
Ok, Ill use typeof variable !== 'undefined' for undefined variables and  if(variable) for checking if variable is not null.

**Comment by erilyth** [comment]
When I use typeof variable !== 'undefined' it doesn't work for all cases, so I looked up a bit more and found out the correct way to use this was typeof(variable) !== "undefined" and this worked out just fine.

**Comment by walterbender** [comment]
Yes.. you need the ()s

On Fri, Dec 11, 2015 at 1:15 PM, Batchu Venkat Vishal <
notifications@github.com> wrote:

> When I use typeof variable !== 'undefined' it doesn't work for all cases,
> so I looked up a bit more and found out the correct way to use this was
> typeof(variable) !== "undefined" and this worked out just fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/246#issuecomment-164007645>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by erilyth** [comment]
Is the PR fine or anything else needs to be done?

**Comment by walterbender** [comment]
Could you please consolidate the commits into one patch? Then I think we
are good to go :)

On Fri, Dec 11, 2015 at 11:46 PM, Batchu Venkat Vishal <
notifications@github.com> wrote:

> Is the PR fine or anything else needs to be done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/246#issuecomment-164110258>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by erilyth** [comment]
Sure Ill squash them into a single patch

**Comment by walterbender** [comment]
Merged by hand.

**Pull request closed without merging**
