### PR TITLE
Text Rotation Issue #233 fixed

### PR DESCRIPTION
**Pull request by sneh1234**

### CODE REVIEW

**Comment by sneh1234** [comment]
It fixes #233

**Comment by walterbender** [comment]
Except for some funny indentation changes you introduced, this looks good. Please resubmit with the indentation matching the style of the rest of the code.

**Comment by sneh1234** [comment]
Now indentation is also fixed

**Comment by walterbender** [comment]
Seems to still be a problem at line 619 of turtle.js

**Comment by sneh1234** [comment]
Sir, 1f7ac9a commit is final . Sorry , for so many mistakes.

**Pull request merged**
