### PR TITLE
fixes 259 and other related issues

### LINKED ISSUE #259: Delete All button should leave only one turtle
But it is not the case 
here is the screen shot -> 
before pressing button - > 

screenshot from 2016-03-05 06 15 59

after pressing button -> 

screenshot from 2016-03-05 06 16 48
 
But Only one turtle should be left.

### PR DESCRIPTION
**Pull request by hemantkasat**
fixes #259 and also issue  " when we delete the moving turtle and then apply forward action then turtle which is in trash moves"

### CODE REVIEW

**Comment by walterbender** [comment]
Doesn't work. Uncaught TypeError: Cannot read property 'trash' of undefined. I think the proper approach is to create a new start block (and corresponding turtle) if the last start block is deleted.

**Comment by hemantkasat** [comment]
@walterbender yes if we delete the last start block then there  is a problem , othere is this was working fine ??

**Comment by hemantkasat** [comment]
if it is working fine for all other cases then we can handle that seperately.

**Comment by walterbender** [comment]
I didn't do an exhaustive set of tests since the first thing I tried raised
an error.

On Sun, Mar 6, 2016 at 4:52 PM, Hemant Kasat <notifications@github.com>
wrote:

> if it is working fine for all other cases then we can handle that
> seperately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/262#issuecomment-193003498>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by hemantkasat** [comment]
@walterbender , i think for other cases it works thought not sure , you check .

**Comment by hemantkasat** [comment]
may be this can address the last start block issue  115cf453c1049e7e38f8830fe33781c19b9263ef , as the last turtle can't be put into trash.

**Comment by walterbender** [comment]
Did you try it? I'll look too.

On Sun, Mar 6, 2016 at 5:14 PM, Hemant Kasat <notifications@github.com>
wrote:

> may be this can address the last start block issue 115cf45
> <https://github.com/walterbender/turtleblocksjs/commit/115cf453c1049e7e38f8830fe33781c19b9263ef>
> , as the last turtle can't be put into trash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/262#issuecomment-193006162>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by hemantkasat** [comment]
i tried it , i think it works fine.

**Comment by walterbender** [comment]
Seems to work for me too. Can you submit a new PR with all the changes in
one commit?

On Sun, Mar 6, 2016 at 5:20 PM, Hemant Kasat <notifications@github.com>
wrote:

> i tried it , i think it works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/pull/262#issuecomment-193007453>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by hemantkasat** [comment]
yeah sure .

**Pull request closed without merging**
