### PR TITLE
added carbon calculator

### PR DESCRIPTION
**Pull request by sanatankc**
I have tried to add many blocks. I kept it time agnostic too, so it would net get much confusing hopefully.

### CODE REVIEW

**Comment by walterbender** [comment]
The basic mechanics seems to be in place. But I think it needs to be populated by more examples: travel by car, by train, by plane, by bicycle, by walking; lighting, heating and AC, number of rooms, what kind of food you consume, etc.

Can you use graphics blocks for these like in the nutrition plugin?

Also, there seems to be something funny going on with your icon -- it displays very large.

**Comment by sanatankc** [comment]
> The basic mechanics seems to be in place. But I think it needs to be populated by more examples: travel by car, by train, by plane, by bicycle, by walking; lighting, heating and AC, number of rooms, what kind of food you consume, etc.

I think there is car, train plane and bus.

> Can you use graphics blocks for these like in the nutrition plugin?
I actually tried to do that first but failed to put arg in mediaBlock and oneArgMathBlock doesn't resize well with images.

> Also, there seems to be something funny going on with your icon -- it displays very large.

It is not displaying large in my case. Can you send a screenshot.

**Comment by walterbender** [comment]
screenshot from 2018-01-05 07-33-00

**Comment by walterbender** [comment]
There is also something wrong with the fluorescent block.

**Comment by walterbender** [comment]
could be related to missing ;s at the end of many block.value = lines in the .rtp

**Comment by walterbender** [comment]
actually, it is a missing /
/* macro:lamp *//

**Comment by sanatankc** [comment]
yeah, just, saw that. Fixed.

**Pull request merged**
