### PR TITLE
added random_quote plugin

### PR DESCRIPTION
**Pull request by sanatankc**

### CODE REVIEW

**Comment by walterbender** [comment]
Will your while loop exit if there is an error fetching the quote? Doesn't look like it will.

**Comment by walterbender** [comment]
Also, it should time out after awhile in any case or there is a risk that the program will hang.

**Comment by sanatankc** [comment]
It will exit (see catch). 

You are right about timeout I will add it.

**Comment by walterbender** [comment]
I didn't catch the catch :P

**Comment by walterbender** [comment]
You need to be sure to add semicolons at the ends of lines because when the code is converted to JSON, it runs the lines together.

You should use the ErrorMsgs mechanism to inform the user that it fails.

A 2 minute timeout is too long. It should be 10s of seconds at most, even for a slow connection (a slow connection will not want to use this plugin).

I cannot successfully get it to return a quote. Have you gotten it to work?

**Comment by sanatankc** [comment]
Sorry, I mistakenly tested version last time.

I just also found another bug that it is blocking main thread so fetch is also blocking. (which was working earlier for some reason). :/

By Error Msg mechanism you mean like I did in catch?

**Comment by walterbender** [comment]
By error message, I meant the way that most other blocks typically report errors:

this.errorMsg('your error message", blk);

**Comment by sanatankc** [comment]
I have updated logic. So instead of blocking while loop , there is a default quote which will be printed first time and fetched quotes subsequently. Also, I have changed API service, as earlier there were many problems with the API. I have added error-handling mechanism and it doesn't actually need an timeout. It is as fast as print normal text with a downside of printing same quote as default.

**Pull request merged**
