### PR TITLE
fixes #259

### LINKED ISSUE #259: Delete All button should leave only one turtle
But it is not the case 
here is the screen shot -> 
before pressing button - > 

screenshot from 2016-03-05 06 15 59

after pressing button -> 

screenshot from 2016-03-05 06 16 48
 
But Only one turtle should be left.

### PR DESCRIPTION
**Pull request by hemantkasat**
fixes #259

### CODE REVIEW

**Comment by hemantkasat** [comment]
@walterbender  , i came across an issue with my previous implementation  to stop deleting the last turtle so changed the commit little bit.

**Comment by hemantkasat** [comment]
@walterbender  sorry for so many mistakes

**Comment by hemantkasat** [comment]
i have changed the commit according to you said.

**Comment by hemantkasat** [comment]
@walterbender   review !!

**Comment by walterbender** [comment]
Looks good. (Sorry for the delay; I didn't see that you had updated the PR.)

**Comment by hemantkasat** [comment]
@walterbender , there is same issue which this PR addresses(issue is not the title of the issue #259 )  in musicblocks also , so should i create an issue then submit a PR or i can directly submit it.

**Comment by walterbender** [comment]
I don't understand.

**Pull request merged**
