### PR TITLE
Basic protoblock palette scrolling

### PR DESCRIPTION
**Pull request by SAMdroid-apps**

### CODE REVIEW

**Comment by walterbender** [comment]
This works except it seems to suffer from the same problem as the menu buttons: if the palette is just one item longer than the screen height, it doesn't scroll. If it is more than one item longer, it does scroll.

Also, for both, we need to indicate to the user that scrolling is available.

**Comment by SAMdroid-apps** [comment]
>  This works except it seems to suffer from the same problem as the menu buttons: if the palette is just one item longer than the screen height, it doesn't scroll. If it is more than one item longer, it does scroll.

I will look into that :)

>  Also, for both, we need to indicate to the user that scrolling is available.

Yes.  Here is my design idea.  Change the calculation of the height of the palette so you have 1/2 of the bottom block visible.  A bit like the ABC iView app:



What do you think?

**Comment by walterbender** [comment]
Makes sense.  Will you add an offset at the top if need be?

**Comment by SAMdroid-apps** [comment]
No, I will change the height calculation

**Comment by SAMdroid-apps** [comment]
@walterbender I just pushed the new changes

**Pull request merged**
