### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by yudeelawson**

### CODE REVIEW

**Comment by yudeelawson** [comment]
Please sir i don't seem to understand what you mean,Is it not good enough?

**Comment by walterbender** [comment]
Your pull request is fine now. I merged it. Thanks.

**Comment by yudeelawson** [comment]
Please I am very Sorry to disturb you, but sir my task has not been
approved!

**Comment by walterbender** [comment]
That is because you did not resubmit the task for review, so I cannot approve it. Please submit for review in the GCI UI.

**Pull request merged**
